name = "vc-incident-watch"
compatibility_date = "2024-11-01"
pages_build_output_dir = "."

kv_namespaces = [
  { binding = "VCWATCH_KV", id = "REPLACE_WITH_KV_ID" }
]

[vars]
ADMIN_TOKEN = "REPLACE_ME"
TWILIO_ACCOUNT_SID = "REPLACE_ME"
TWILIO_AUTH_TOKEN = "REPLACE_ME"
TWILIO_FROM = "REPLACE_ME"
VAPID_PUBLIC_KEY = "REPLACE_ME"
VAPID_PRIVATE_KEY = "REPLACE_ME"
VAPID_SUBJECT = "mailto:you@vcwatch.org"
PUSH_TEST_SECRET = "REPLACE_ME"
PUSH_NOTIFY_SECRET = "REPLACE_ME"
ENABLE_PUSH_TEST = "false"
